root: true
parser: '@typescript-eslint/parser'
# parserOptions:
#   project: ./tsconfig.json
env:
  es6: true
ignorePatterns:
  - node_modules
  - build
  - coverage
plugins:
  - import
  - eslint-comments
  - functional
extends:
  - 'eslint:recommended'
  - 'plugin:eslint-comments/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/typescript'
  - 'plugin:functional/lite'
  - prettier
  - prettier/@typescript-eslint
globals:
  BigInt: true
  console: true
  WebAssembly: true
rules:
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  comma-dangle: 0
  eslint-comments/disable-enable-pair:
    - error
    - allowWholeFile: true
  eslint-comments/no-unused-disable: error
  import/order:
    - error
    - newlines-between: always
      alphabetize:
        order: asc
  max-len:
    - error
    - code: 120
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  semi: 0
  sort-imports:
    - error
    - ignoreDeclarationSort: true
      ignoreCase: true
